name: fnal

on: 
  push:
    branches: ["main"]

 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

     - name run hello world
       run: echo "hello world"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run hello world
        run: echo "hello world"
        
    
