name: CI with Linting & Tests


on:
  push:
    branches: ["main"]



jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
      - uses: actions/checkout@v3
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: npm test
